# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-08 12:24
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Sale_Bill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('buyer_brand', models.CharField(max_length=50)),
                ('buyer_address', models.CharField(max_length=200)),
                ('buyer_agent', models.CharField(max_length=100)),
                ('total_head', models.PositiveIntegerField()),
                ('total_weight', models.DecimalField(decimal_places=2, max_digits=8)),
                ('avg_weight', models.DecimalField(decimal_places=2, max_digits=8)),
                ('gross_total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('avg_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('commission', models.DecimalField(decimal_places=2, max_digits=10)),
                ('feed', models.DecimalField(decimal_places=2, max_digits=10)),
                ('freight', models.DecimalField(decimal_places=2, max_digits=10)),
                ('other', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
