# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-08 13:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cattle', '0002_auto_20170108_1550'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sale_bill',
            old_name='author',
            new_name='creator',
        ),
        migrations.AlterField(
            model_name='sale_bill',
            name='avg_price',
            field=models.DecimalField(decimal_places=2, editable=False, max_digits=10),
        ),
        migrations.AlterField(
            model_name='sale_bill',
            name='avg_weight',
            field=models.DecimalField(decimal_places=2, editable=False, max_digits=8),
        ),
        migrations.AlterField(
            model_name='sale_bill',
            name='gross_total',
            field=models.DecimalField(decimal_places=2, editable=False, max_digits=10),
        ),
        migrations.AlterField(
            model_name='sale_bill',
            name='total',
            field=models.DecimalField(decimal_places=2, editable=False, max_digits=10),
        ),
        migrations.AlterField(
            model_name='sale_bill',
            name='total_weight',
            field=models.DecimalField(decimal_places=2, editable=False, max_digits=8),
        ),
    ]
