# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-08 15:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cattle', '0004_auto_20170108_1625'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchase',
            name='price_head',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8),
        ),
        migrations.AlterField(
            model_name='sale_bill',
            name='commission',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='sale_bill',
            name='feed',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='sale_bill',
            name='freight',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='sale_bill',
            name='other',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10),
        ),
    ]
