# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-08 15:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cattle', '0005_auto_20170108_1703'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sale_bill',
            name='avg_price',
            field=models.DecimalField(blank=True, decimal_places=2, editable=False, max_digits=10),
        ),
        migrations.AlterField(
            model_name='sale_bill',
            name='avg_weight',
            field=models.DecimalField(blank=True, decimal_places=2, editable=False, max_digits=8),
        ),
        migrations.AlterField(
            model_name='sale_bill',
            name='gross_total',
            field=models.DecimalField(blank=True, decimal_places=2, editable=False, max_digits=10),
        ),
        migrations.AlterField(
            model_name='sale_bill',
            name='total',
            field=models.DecimalField(blank=True, decimal_places=2, editable=False, max_digits=10),
        ),
        migrations.AlterField(
            model_name='sale_bill',
            name='total_head',
            field=models.PositiveIntegerField(blank=True, editable=False),
        ),
        migrations.AlterField(
            model_name='sale_bill',
            name='total_weight',
            field=models.DecimalField(blank=True, decimal_places=2, editable=False, max_digits=8),
        ),
    ]
